import type { Word } from "./Reader";

export const extractText = `
  »Gegen Weihnachten des Jahres 1844, als mein ältester Sohn drei Jahre
alt war, ging ich in die Stadt, um demselben zum Festgeschenke ein
Bilderbuch zu kaufen, wie es der Fassungskraft des kleinen menschlichen
Wesens in solchem Alter entsprechend schien. Aber was fand ich? Lange
Erzählungen oder alberne Bildersammlungen, moralische Geschichten, die
mit ermahnenden Vorschriften begannen und schlossen, wie: »Das brave
Kind muß wahrhaft sein«; oder: »Brave Kinder müssen sich reinlich
halten« etc. – Als ich nun gar endlich ein Foliobuch fand, in welchem
eine Bank, ein Stuhl, ein Topf und vieles andere, was wächst oder
gemacht wird, ein wahres Weltrepertorium, abgezeichnet war, und wo bei
jedem Bild fein säuberlich zu lesen war: die Hälfte, ein Drittel, oder
ein Zehntel der natürlichen Größe, da war es mit meiner Geduld aus.
Einem Kind, dem man eine Bank zeichnet, und das sich daran erfreuen
soll, ist dies eine Bank, eine wirkliche Bank. Und von der wirklichen
Lebensgröße der Bank, hat und braucht das Kind gar keinen Begriff zu
haben. Abstrakt denkt ja das Kind noch gar nicht, und die allgemeine
Warnung: »Du sollst nicht lügen!« hat wenig ausgerichtet im Vergleich
mit der Geschichte: »Fritz, Fritz, die Brücke kommt!«

Als ich damals heimkam, hatte ich aber _doch_ ein Buch mitgebracht; ich
überreichte es meiner Frau mit den Worten: »Hier ist das gewünschte Buch
für den Jungen!« Sie nahm es und rief verwundert: »Das ist ja ein
Schreibheft mit leeren weißen Blättern!« »Nun ja, da wollen wir ein Buch
daraus machen!«

Damit ging es nun aber so zu. Ich war damals, neben meinem Amt als Arzt
der Irrenanstalt, auch noch auf Praxis in der Stadt angewiesen. Nun ist
es ein eigen Ding um den Verkehr des Arztes mit Kindern von drei bis
sechs Jahren. In gesunden Tagen wird der Arzt und der Schornsteinfeger
gar oft als Erziehungsmittel gebraucht: »Kind, wenn du nicht brav bist,
kommt der Schornsteinfeger und holt dich!« oder: »Kind, wenn du zu viel
davon issest, so kommt der Doktor und gibt dir bittere Arznei, oder
setzt dir gar Blutegel an!« Die Folge ist, daß, wenn in schlimmen Zeiten
der Doktor gerufen in das Zimmer tritt, der kleine kranke Engel zu
heulen, sich zu wehren, und um sich zu treten anfängt. Eine Untersuchung
des Zustandes ist schlechterdings unmöglich; stundenlang aber kann der
Arzt nicht den Beruhigenden, Besänftigenden machen. Da half mir
gewöhnlich rasch ein Blättchen Papier und Bleistift; eine der
Geschichten wie sie in dem Buche stehen, wird rasch erfunden, mit drei
Strichen gezeichnet, und dazu möglichst lebendig erzählt. Der wilde
Oppositionsmann wird ruhig, die Tränen trocknen, und der Arzt kann
spielend seine Pflicht tun.

[Illustration: Heinrich Hoffmann]

So entstanden die meisten dieser tollen Szenen, und ich schöpfte sie aus
vorhandenem Vorrate; einiges wurde später dazu erfunden, die Bilder
wurden mit derselben Feder und Tinte gezeichnet, mit der ich erst die
Reime geschrieben hatte, alles unmittelbar und ohne schriftstellerische
Absichtlichkeit. Das Heft wurde eingebunden und auf den Weihnachtstisch
gelegt. Die Wirkung auf den beschenkten Knaben war die erwartete; aber
unerwartet war die auf einige erwachsene Freunde, die das Büchlein zu
Gesicht bekamen. Von allen Seiten wurde ich aufgefordert, es drucken zu
lassen und es zu veröffentlichen. Ich lehnte es anfangs ab; ich hatte
nicht im Entferntesten daran gedacht, als Kinderschriftsteller und
Bilderbüchler aufzutreten. Fast wider Willen wurde ich dazu gebracht als
ich einst in einer literarischen Abendgesellschaft mit dem einen meiner
jetzigen Verleger gemütlich bei der Flasche zusammensaß. Und so trat das
bescheidene Hauskind plötzlich hinaus in die weite offene Welt und
machte nun seine Reise, ich kann wohl sagen, um die Welt, und ist heute
seit einunddreißig Jahren bis zur _hundertsten_ Auflage gelangt. Von
Uebersetzungen ist mir bis jetzt eine englische, holländische, dänische,
schwedische, russische, französische, italienische, spanische und eine
portugiesische (für Brasilien) zu Gesicht gekommen.
  `;

export const extract: Word[] = [
  { text: "Gegen", followingPunctuation: " ", translation: "towards" },
  { text: "Weihnachten", followingPunctuation: " ", translation: "Christmas" },
  { text: "des", followingPunctuation: " ", translation: "of the" },
  { text: "Jahres", followingPunctuation: " ", translation: "year" },
  { text: "1844", followingPunctuation: ", ", translation: "1844" },
  { text: "als", followingPunctuation: " ", translation: "when" },
  { text: "mein", followingPunctuation: " ", translation: "my" },
  { text: "ältester", followingPunctuation: " ", translation: "oldest" },
  { text: "Sohn", followingPunctuation: " ", translation: "son" },
  { text: "drei", followingPunctuation: " ", translation: "three" },
  { text: "Jahre", followingPunctuation: " ", translation: "years" },
  { text: "alt", followingPunctuation: " ", translation: "old" },
  { text: "war", followingPunctuation: ", ", translation: "was" },
  { text: "ging", followingPunctuation: " ", translation: "went" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Stadt", followingPunctuation: ", ", translation: "city" },
  { text: "um", followingPunctuation: " ", translation: "in order to" },
  { text: "demselben", followingPunctuation: " ", translation: "the same" },
  { text: "zum", followingPunctuation: " ", translation: "for the" },
  {
    text: "Festgeschenke",
    followingPunctuation: " ",
    translation: "holiday gift",
  },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  {
    text: "Bilderbuch",
    followingPunctuation: " ",
    translation: "picture book",
  },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "kaufen", followingPunctuation: ", ", translation: "buy" },
  { text: "wie", followingPunctuation: " ", translation: "as" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  {
    text: "Fassungskraft",
    followingPunctuation: " ",
    translation: "comprehension",
  },
  { text: "des", followingPunctuation: " ", translation: "of the" },
  { text: "kleinen", followingPunctuation: " ", translation: "small" },
  { text: "menschlichen", followingPunctuation: " ", translation: "human" },
  { text: "Wesens", followingPunctuation: " ", translation: "being" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "solchem", followingPunctuation: " ", translation: "such" },
  { text: "Alter", followingPunctuation: " ", translation: "age" },
  {
    text: "entsprechend",
    followingPunctuation: " ",
    translation: "appropriate",
  },
  { text: "schien", followingPunctuation: ". ", translation: "seemed" },
  { text: "Aber", followingPunctuation: " ", translation: "but" },
  { text: "was", followingPunctuation: " ", translation: "what" },
  { text: "fand", followingPunctuation: " ", translation: "found" },
  { text: "ich", followingPunctuation: "? ", translation: "I" },
  { text: "Lange", followingPunctuation: " ", translation: "long" },
  { text: "Erzählungen", followingPunctuation: " ", translation: "stories" },
  { text: "oder", followingPunctuation: " ", translation: "or" },
  { text: "alberne", followingPunctuation: " ", translation: "silly" },
  {
    text: "Bildersammlungen",
    followingPunctuation: ", ",
    translation: "picture collections",
  },
  { text: "moralische", followingPunctuation: " ", translation: "moral" },
  { text: "Geschichten", followingPunctuation: ", ", translation: "stories" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  {
    text: "ermahnenden",
    followingPunctuation: " ",
    translation: "admonishing",
  },
  { text: "Vorschriften", followingPunctuation: " ", translation: "rules" },
  { text: "begannen", followingPunctuation: " ", translation: "began" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "schlossen", followingPunctuation: ", ", translation: "ended" },
  { text: "wie", followingPunctuation: ": »", translation: "as" },
  { text: "Das", followingPunctuation: " ", translation: "the" },
  { text: "brave", followingPunctuation: " ", translation: "good" },
  { text: "Kind", followingPunctuation: " ", translation: "child" },
  { text: "muß", followingPunctuation: " ", translation: "must" },
  { text: "wahrhaft", followingPunctuation: " ", translation: "truthful" },
  { text: "sein", followingPunctuation: "«; ", translation: "be" },
  { text: "oder", followingPunctuation: ": »", translation: "or" },
  { text: "Brave", followingPunctuation: " ", translation: "good" },
  { text: "Kinder", followingPunctuation: " ", translation: "children" },
  { text: "müssen", followingPunctuation: " ", translation: "must" },
  { text: "sich", followingPunctuation: " ", translation: "themselves" },
  { text: "reinlich", followingPunctuation: " ", translation: "clean" },
  { text: "halten", followingPunctuation: "« ", translation: "keep" },
  { text: "etc", followingPunctuation: ". – ", translation: "etc" },
  { text: "Als", followingPunctuation: " ", translation: "when" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "nun", followingPunctuation: " ", translation: "now" },
  { text: "gar", followingPunctuation: " ", translation: "at all" },
  { text: "endlich", followingPunctuation: " ", translation: "finally" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Foliobuch", followingPunctuation: " ", translation: "folio book" },
  { text: "fand", followingPunctuation: ", ", translation: "found" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "welchem", followingPunctuation: " ", translation: "which" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "Bank", followingPunctuation: ", ", translation: "bench" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Stuhl", followingPunctuation: ", ", translation: "chair" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Topf", followingPunctuation: " ", translation: "pot" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "vieles", followingPunctuation: " ", translation: "many things" },
  { text: "andere", followingPunctuation: ", ", translation: "other" },
  { text: "was", followingPunctuation: " ", translation: "what" },
  { text: "wächst", followingPunctuation: " ", translation: "grows" },
  { text: "oder", followingPunctuation: " ", translation: "or" },
  { text: "gemacht", followingPunctuation: " ", translation: "made" },
  { text: "wird", followingPunctuation: ", ", translation: "is" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "wahres", followingPunctuation: " ", translation: "true" },
  {
    text: "Weltrepertorium",
    followingPunctuation: ", ",
    translation: "world repertory",
  },
  { text: "abgezeichnet", followingPunctuation: " ", translation: "drawn" },
  { text: "war", followingPunctuation: ", ", translation: "was" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "wo", followingPunctuation: " ", translation: "where" },
  { text: "bei", followingPunctuation: " ", translation: "at" },
  { text: "jedem", followingPunctuation: " ", translation: "every" },
  { text: "Bild", followingPunctuation: " ", translation: "picture" },
  { text: "fein", followingPunctuation: " ", translation: "neatly" },
  { text: "säuberlich", followingPunctuation: " ", translation: "carefully" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "lesen", followingPunctuation: " ", translation: "read" },
  { text: "war", followingPunctuation: ": ", translation: "was" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Hälfte", followingPunctuation: ", ", translation: "half" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Drittel", followingPunctuation: ", ", translation: "third" },
  { text: "oder", followingPunctuation: " ", translation: "or" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Zehntel", followingPunctuation: " ", translation: "tenth" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "natürlichen", followingPunctuation: " ", translation: "natural" },
  { text: "Größe", followingPunctuation: ", ", translation: "size" },
  { text: "da", followingPunctuation: " ", translation: "then" },
  { text: "war", followingPunctuation: " ", translation: "was" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "meiner", followingPunctuation: " ", translation: "my" },
  { text: "Geduld", followingPunctuation: " ", translation: "patience" },
  { text: "aus", followingPunctuation: ". ", translation: "over" },
  { text: "Einem", followingPunctuation: " ", translation: "a" },
  { text: "Kind", followingPunctuation: ", ", translation: "child" },
  { text: "dem", followingPunctuation: " ", translation: "the" },
  { text: "man", followingPunctuation: " ", translation: "one" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "Bank", followingPunctuation: " ", translation: "bench" },
  { text: "zeichnet", followingPunctuation: ", ", translation: "draws" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "sich", followingPunctuation: " ", translation: "themselves" },
  { text: "daran", followingPunctuation: " ", translation: "in it" },
  { text: "erfreuen", followingPunctuation: " ", translation: "delight" },
  { text: "soll", followingPunctuation: ", ", translation: "should" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "dies", followingPunctuation: " ", translation: "this" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "Bank", followingPunctuation: ", ", translation: "bench" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "wirkliche", followingPunctuation: " ", translation: "real" },
  { text: "Bank", followingPunctuation: ". ", translation: "bench" },
  { text: "Und", followingPunctuation: " ", translation: "and" },
  { text: "von", followingPunctuation: " ", translation: "of" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "wirklichen", followingPunctuation: " ", translation: "real" },
  { text: "Lebensgröße", followingPunctuation: " ", translation: "life-size" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Bank", followingPunctuation: ", ", translation: "bench" },
  { text: "hat", followingPunctuation: " ", translation: "has" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "braucht", followingPunctuation: " ", translation: "needs" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "Kind", followingPunctuation: " ", translation: "child" },
  { text: "gar", followingPunctuation: " ", translation: "at all" },
  { text: "keinen", followingPunctuation: " ", translation: "no" },
  { text: "Begriff", followingPunctuation: " ", translation: "concept" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "haben", followingPunctuation: ". ", translation: "have" },
  { text: "Abstrakt", followingPunctuation: " ", translation: "abstractly" },
  { text: "denkt", followingPunctuation: " ", translation: "thinks" },
  { text: "ja", followingPunctuation: " ", translation: "indeed" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "Kind", followingPunctuation: " ", translation: "child" },
  { text: "noch", followingPunctuation: " ", translation: "still" },
  { text: "gar", followingPunctuation: " ", translation: "at all" },
  { text: "nicht", followingPunctuation: ", ", translation: "not" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "allgemeine", followingPunctuation: " ", translation: "general" },
  { text: "Warnung", followingPunctuation: ": »", translation: "warning" },
  { text: "Du", followingPunctuation: " ", translation: "you" },
  { text: "sollst", followingPunctuation: " ", translation: "should" },
  { text: "nicht", followingPunctuation: " ", translation: "not" },
  { text: "lügen", followingPunctuation: "!« ", translation: "lie" },
  { text: "hat", followingPunctuation: " ", translation: "has" },
  { text: "wenig", followingPunctuation: " ", translation: "little" },
  {
    text: "ausgerichtet",
    followingPunctuation: " ",
    translation: "accomplished",
  },
  { text: "im", followingPunctuation: " ", translation: "in the" },
  { text: "Vergleich", followingPunctuation: " ", translation: "comparison" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Geschichte", followingPunctuation: ": »", translation: "story" },
  { text: "Fritz", followingPunctuation: ", ", translation: "Fritz" },
  { text: "Fritz", followingPunctuation: ", ", translation: "Fritz" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Brücke", followingPunctuation: " ", translation: "bridge" },
  { text: "kommt", followingPunctuation: "!«\n\n", translation: "comes" },
  { text: "Als", followingPunctuation: " ", translation: "when" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "damals", followingPunctuation: " ", translation: "at that time" },
  { text: "heimkam", followingPunctuation: ", ", translation: "came home" },
  { text: "hatte", followingPunctuation: " ", translation: "had" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "aber", followingPunctuation: " ", translation: "but" },
  { text: "doch", followingPunctuation: " ", translation: "nevertheless" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Buch", followingPunctuation: " ", translation: "book" },
  {
    text: "mitgebracht",
    followingPunctuation: "; ",
    translation: "brought along",
  },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "überreichte", followingPunctuation: " ", translation: "presented" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "meiner", followingPunctuation: " ", translation: "my" },
  { text: "Frau", followingPunctuation: " ", translation: "wife" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  { text: "Worten", followingPunctuation: ": »", translation: "words" },
  { text: "Hier", followingPunctuation: " ", translation: "here" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "gewünschte", followingPunctuation: " ", translation: "desired" },
  { text: "Buch", followingPunctuation: " ", translation: "book" },
  { text: "für", followingPunctuation: " ", translation: "for" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  { text: "Jungen", followingPunctuation: "!« ", translation: "boy" },
  { text: "Sie", followingPunctuation: " ", translation: "she" },
  { text: "nahm", followingPunctuation: " ", translation: "took" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "rief", followingPunctuation: " ", translation: "called out" },
  {
    text: "verwundert",
    followingPunctuation: ": »",
    translation: "astonished",
  },
  { text: "Das", followingPunctuation: " ", translation: "the" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "ja", followingPunctuation: " ", translation: "indeed" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Schreibheft", followingPunctuation: " ", translation: "notebook" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "leeren", followingPunctuation: " ", translation: "empty" },
  { text: "weißen", followingPunctuation: " ", translation: "white" },
  { text: "Blättern", followingPunctuation: "!« »", translation: "pages" },
  { text: "Nun", followingPunctuation: " ", translation: "now" },
  { text: "ja", followingPunctuation: ", ", translation: "indeed" },
  { text: "da", followingPunctuation: " ", translation: "then" },
  { text: "wollen", followingPunctuation: " ", translation: "want" },
  { text: "wir", followingPunctuation: " ", translation: "we" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Buch", followingPunctuation: " ", translation: "book" },
  { text: "daraus", followingPunctuation: " ", translation: "from it" },
  { text: "machen", followingPunctuation: "!«\n\n", translation: "make" },
  { text: "Damit", followingPunctuation: " ", translation: "with that" },
  { text: "ging", followingPunctuation: " ", translation: "went" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "nun", followingPunctuation: " ", translation: "now" },
  { text: "aber", followingPunctuation: " ", translation: "but" },
  { text: "so", followingPunctuation: " ", translation: "so" },
  { text: "zu", followingPunctuation: ". ", translation: "to" },
  { text: "Ich", followingPunctuation: " ", translation: "I" },
  { text: "war", followingPunctuation: " ", translation: "was" },
  { text: "damals", followingPunctuation: ", ", translation: "at that time" },
  { text: "neben", followingPunctuation: " ", translation: "beside" },
  { text: "meinem", followingPunctuation: " ", translation: "my" },
  { text: "Amt", followingPunctuation: " ", translation: "office" },
  { text: "als", followingPunctuation: " ", translation: "when" },
  { text: "Arzt", followingPunctuation: " ", translation: "doctor" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Irrenanstalt", followingPunctuation: ", ", translation: "asylum" },
  { text: "auch", followingPunctuation: " ", translation: "also" },
  { text: "noch", followingPunctuation: " ", translation: "still" },
  { text: "auf", followingPunctuation: " ", translation: "on" },
  { text: "Praxis", followingPunctuation: " ", translation: "practice" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Stadt", followingPunctuation: " ", translation: "city" },
  { text: "angewiesen", followingPunctuation: ". ", translation: "dependent" },
  { text: "Nun", followingPunctuation: " ", translation: "now" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "eigen", followingPunctuation: " ", translation: "peculiar" },
  { text: "Ding", followingPunctuation: " ", translation: "thing" },
  { text: "um", followingPunctuation: " ", translation: "in order to" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  { text: "Verkehr", followingPunctuation: " ", translation: "dealings" },
  { text: "des", followingPunctuation: " ", translation: "of the" },
  { text: "Arztes", followingPunctuation: " ", translation: "doctor's" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "Kindern", followingPunctuation: " ", translation: "children" },
  { text: "von", followingPunctuation: " ", translation: "of" },
  { text: "drei", followingPunctuation: " ", translation: "three" },
  { text: "bis", followingPunctuation: " ", translation: "until" },
  { text: "sechs", followingPunctuation: " ", translation: "six" },
  { text: "Jahren", followingPunctuation: ". ", translation: "years" },
  { text: "In", followingPunctuation: " ", translation: "in" },
  { text: "gesunden", followingPunctuation: " ", translation: "healthy" },
  { text: "Tagen", followingPunctuation: " ", translation: "days" },
  { text: "wird", followingPunctuation: " ", translation: "is" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Arzt", followingPunctuation: " ", translation: "doctor" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  {
    text: "Schornsteinfeger",
    followingPunctuation: " ",
    translation: "chimney sweep",
  },
  { text: "gar", followingPunctuation: " ", translation: "at all" },
  { text: "oft", followingPunctuation: " ", translation: "often" },
  { text: "als", followingPunctuation: " ", translation: "when" },
  {
    text: "Erziehungsmittel",
    followingPunctuation: " ",
    translation: "means of discipline",
  },
  { text: "gebraucht", followingPunctuation: ": »", translation: "used" },
  { text: "Kind", followingPunctuation: ", ", translation: "child" },
  { text: "wenn", followingPunctuation: " ", translation: "when" },
  { text: "du", followingPunctuation: " ", translation: "you" },
  { text: "nicht", followingPunctuation: " ", translation: "not" },
  { text: "brav", followingPunctuation: " ", translation: "good" },
  { text: "bist", followingPunctuation: ", ", translation: "are" },
  { text: "kommt", followingPunctuation: " ", translation: "comes" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  {
    text: "Schornsteinfeger",
    followingPunctuation: " ",
    translation: "chimney sweep",
  },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "holt", followingPunctuation: " ", translation: "fetches" },
  { text: "dich", followingPunctuation: "!« ", translation: "you" },
  { text: "oder", followingPunctuation: ": »", translation: "or" },
  { text: "Kind", followingPunctuation: ", ", translation: "child" },
  { text: "wenn", followingPunctuation: " ", translation: "when" },
  { text: "du", followingPunctuation: " ", translation: "you" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "viel", followingPunctuation: " ", translation: "much" },
  { text: "davon", followingPunctuation: " ", translation: "of it" },
  { text: "issest", followingPunctuation: ", ", translation: "eat" },
  { text: "so", followingPunctuation: " ", translation: "so" },
  { text: "kommt", followingPunctuation: " ", translation: "comes" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Doktor", followingPunctuation: " ", translation: "doctor" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "gibt", followingPunctuation: " ", translation: "gives" },
  { text: "dir", followingPunctuation: " ", translation: "you" },
  { text: "bittere", followingPunctuation: " ", translation: "bitter" },
  { text: "Arznei", followingPunctuation: ", ", translation: "medicine" },
  { text: "oder", followingPunctuation: " ", translation: "or" },
  { text: "setzt", followingPunctuation: " ", translation: "places" },
  { text: "dir", followingPunctuation: " ", translation: "you" },
  { text: "gar", followingPunctuation: " ", translation: "at all" },
  { text: "Blutegel", followingPunctuation: " ", translation: "leeches" },
  { text: "an", followingPunctuation: "!« ", translation: "on" },
  { text: "Die", followingPunctuation: " ", translation: "the" },
  { text: "Folge", followingPunctuation: " ", translation: "consequence" },
  { text: "ist", followingPunctuation: ", ", translation: "is" },
  { text: "daß", followingPunctuation: ", ", translation: "that" },
  { text: "wenn", followingPunctuation: " ", translation: "when" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "schlimmen", followingPunctuation: " ", translation: "bad" },
  { text: "Zeiten", followingPunctuation: " ", translation: "times" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Doktor", followingPunctuation: " ", translation: "doctor" },
  { text: "gerufen", followingPunctuation: " ", translation: "called" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "Zimmer", followingPunctuation: " ", translation: "room" },
  { text: "tritt", followingPunctuation: ", ", translation: "steps" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "kleine", followingPunctuation: " ", translation: "little" },
  { text: "kranke", followingPunctuation: " ", translation: "sick" },
  { text: "Engel", followingPunctuation: " ", translation: "angel" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "heulen", followingPunctuation: ", ", translation: "howl" },
  { text: "sich", followingPunctuation: " ", translation: "themselves" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "wehren", followingPunctuation: ", ", translation: "defend" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "um", followingPunctuation: " ", translation: "in order to" },
  { text: "sich", followingPunctuation: " ", translation: "themselves" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "treten", followingPunctuation: " ", translation: "kick" },
  { text: "anfängt", followingPunctuation: ". ", translation: "begins" },
  { text: "Eine", followingPunctuation: " ", translation: "a" },
  {
    text: "Untersuchung",
    followingPunctuation: " ",
    translation: "examination",
  },
  { text: "des", followingPunctuation: " ", translation: "of the" },
  { text: "Zustandes", followingPunctuation: " ", translation: "condition" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  {
    text: "schlechterdings",
    followingPunctuation: " ",
    translation: "absolutely",
  },
  { text: "unmöglich", followingPunctuation: "; ", translation: "impossible" },
  { text: "stundenlang", followingPunctuation: " ", translation: "for hours" },
  { text: "aber", followingPunctuation: " ", translation: "but" },
  { text: "kann", followingPunctuation: " ", translation: "can" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Arzt", followingPunctuation: " ", translation: "doctor" },
  { text: "nicht", followingPunctuation: " ", translation: "not" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  {
    text: "Beruhigenden",
    followingPunctuation: ", ",
    translation: "calming one",
  },
  {
    text: "Besänftigenden",
    followingPunctuation: " ",
    translation: "soothing one",
  },
  { text: "machen", followingPunctuation: ". ", translation: "make" },
  { text: "Da", followingPunctuation: " ", translation: "then" },
  { text: "half", followingPunctuation: " ", translation: "helped" },
  { text: "mir", followingPunctuation: " ", translation: "me" },
  { text: "gewöhnlich", followingPunctuation: " ", translation: "usually" },
  { text: "rasch", followingPunctuation: " ", translation: "quickly" },
  { text: "ein", followingPunctuation: " ", translation: "a" },
  { text: "Blättchen", followingPunctuation: " ", translation: "little sheet" },
  { text: "Papier", followingPunctuation: " ", translation: "paper" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "Bleistift", followingPunctuation: "; ", translation: "pencil" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Geschichten", followingPunctuation: " ", translation: "stories" },
  { text: "wie", followingPunctuation: " ", translation: "as" },
  { text: "sie", followingPunctuation: " ", translation: "she" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "dem", followingPunctuation: " ", translation: "the" },
  { text: "Buche", followingPunctuation: " ", translation: "book" },
  { text: "stehen", followingPunctuation: ", ", translation: "stand" },
  { text: "wird", followingPunctuation: " ", translation: "is" },
  { text: "rasch", followingPunctuation: " ", translation: "quickly" },
  { text: "erfunden", followingPunctuation: ", ", translation: "invented" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "drei", followingPunctuation: " ", translation: "three" },
  { text: "Strichen", followingPunctuation: " ", translation: "strokes" },
  { text: "gezeichnet", followingPunctuation: ", ", translation: "drawn" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "dazu", followingPunctuation: " ", translation: "in addition" },
  {
    text: "möglichst",
    followingPunctuation: " ",
    translation: "as much as possible",
  },
  { text: "lebendig", followingPunctuation: " ", translation: "lively" },
  { text: "erzählt", followingPunctuation: ". ", translation: "told" },
  { text: "Der", followingPunctuation: " ", translation: "the" },
  { text: "wilde", followingPunctuation: " ", translation: "wild" },
  {
    text: "Oppositionsmann",
    followingPunctuation: " ",
    translation: "opponent",
  },
  { text: "wird", followingPunctuation: " ", translation: "is" },
  { text: "ruhig", followingPunctuation: ", ", translation: "calm" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Tränen", followingPunctuation: " ", translation: "tears" },
  { text: "trocknen", followingPunctuation: ", ", translation: "dry" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Arzt", followingPunctuation: " ", translation: "doctor" },
  { text: "kann", followingPunctuation: " ", translation: "can" },
  { text: "spielend", followingPunctuation: " ", translation: "playfully" },
  { text: "seine", followingPunctuation: " ", translation: "his" },
  { text: "Pflicht", followingPunctuation: " ", translation: "duty" },
  { text: "tun", followingPunctuation: ".\n\n", translation: "do" },
  { text: "So", followingPunctuation: " ", translation: "so" },
  { text: "entstanden", followingPunctuation: " ", translation: "originated" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "meisten", followingPunctuation: " ", translation: "most" },
  { text: "dieser", followingPunctuation: " ", translation: "these" },
  { text: "tollen", followingPunctuation: " ", translation: "wonderful" },
  { text: "Szenen", followingPunctuation: ", ", translation: "scenes" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "schöpfte", followingPunctuation: " ", translation: "drew" },
  { text: "sie", followingPunctuation: " ", translation: "she" },
  { text: "aus", followingPunctuation: " ", translation: "over" },
  { text: "vorhandenem", followingPunctuation: " ", translation: "existing" },
  { text: "Vorrate", followingPunctuation: "; ", translation: "supply" },
  { text: "einiges", followingPunctuation: " ", translation: "some things" },
  { text: "wurde", followingPunctuation: " ", translation: "was" },
  { text: "später", followingPunctuation: " ", translation: "later" },
  { text: "dazu", followingPunctuation: " ", translation: "in addition" },
  { text: "erfunden", followingPunctuation: ", ", translation: "invented" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Bilder", followingPunctuation: " ", translation: "pictures" },
  { text: "wurden", followingPunctuation: " ", translation: "were" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "derselben", followingPunctuation: " ", translation: "the same" },
  { text: "Feder", followingPunctuation: " ", translation: "pen" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "Tinte", followingPunctuation: " ", translation: "ink" },
  { text: "gezeichnet", followingPunctuation: ", ", translation: "drawn" },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "erst", followingPunctuation: " ", translation: "first" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Reime", followingPunctuation: " ", translation: "rhymes" },
  { text: "geschrieben", followingPunctuation: " ", translation: "written" },
  { text: "hatte", followingPunctuation: ", ", translation: "had" },
  { text: "alles", followingPunctuation: " ", translation: "everything" },
  { text: "unmittelbar", followingPunctuation: " ", translation: "directly" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "ohne", followingPunctuation: " ", translation: "without" },
  {
    text: "schriftstellerische",
    followingPunctuation: " ",
    translation: "literary",
  },
  {
    text: "Absichtlichkeit",
    followingPunctuation: ". ",
    translation: "intentionality",
  },
  { text: "Das", followingPunctuation: " ", translation: "the" },
  { text: "Heft", followingPunctuation: " ", translation: "booklet" },
  { text: "wurde", followingPunctuation: " ", translation: "was" },
  { text: "eingebunden", followingPunctuation: " ", translation: "bound" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "auf", followingPunctuation: " ", translation: "on" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  {
    text: "Weihnachtstisch",
    followingPunctuation: " ",
    translation: "Christmas table",
  },
  { text: "gelegt", followingPunctuation: ". ", translation: "placed" },
  { text: "Die", followingPunctuation: " ", translation: "the" },
  { text: "Wirkung", followingPunctuation: " ", translation: "effect" },
  { text: "auf", followingPunctuation: " ", translation: "on" },
  { text: "den", followingPunctuation: " ", translation: "the" },
  { text: "beschenkten", followingPunctuation: " ", translation: "gifted" },
  { text: "Knaben", followingPunctuation: " ", translation: "boy" },
  { text: "war", followingPunctuation: " ", translation: "was" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "erwartete", followingPunctuation: "; ", translation: "expected" },
  { text: "aber", followingPunctuation: " ", translation: "but" },
  { text: "unerwartet", followingPunctuation: " ", translation: "unexpected" },
  { text: "war", followingPunctuation: " ", translation: "was" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "auf", followingPunctuation: " ", translation: "on" },
  { text: "einige", followingPunctuation: " ", translation: "some" },
  { text: "erwachsene", followingPunctuation: " ", translation: "adult" },
  { text: "Freunde", followingPunctuation: ", ", translation: "friends" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "Büchlein", followingPunctuation: " ", translation: "little book" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "Gesicht", followingPunctuation: " ", translation: "sight" },
  { text: "bekamen", followingPunctuation: ". ", translation: "received" },
  { text: "Von", followingPunctuation: " ", translation: "of" },
  { text: "allen", followingPunctuation: " ", translation: "all" },
  { text: "Seiten", followingPunctuation: " ", translation: "sides" },
  { text: "wurde", followingPunctuation: " ", translation: "was" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "aufgefordert", followingPunctuation: ", ", translation: "urged" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "drucken", followingPunctuation: " ", translation: "print" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "lassen", followingPunctuation: " ", translation: "let" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  {
    text: "veröffentlichen",
    followingPunctuation: ". ",
    translation: "publish",
  },
  { text: "Ich", followingPunctuation: " ", translation: "I" },
  { text: "lehnte", followingPunctuation: " ", translation: "declined" },
  { text: "es", followingPunctuation: " ", translation: "it" },
  { text: "anfangs", followingPunctuation: " ", translation: "initially" },
  { text: "ab", followingPunctuation: "; ", translation: "off" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "hatte", followingPunctuation: " ", translation: "had" },
  { text: "nicht", followingPunctuation: " ", translation: "not" },
  { text: "im", followingPunctuation: " ", translation: "in the" },
  {
    text: "Entferntesten",
    followingPunctuation: " ",
    translation: "slightest",
  },
  { text: "daran", followingPunctuation: " ", translation: "in it" },
  { text: "gedacht", followingPunctuation: ", ", translation: "thought" },
  { text: "als", followingPunctuation: " ", translation: "when" },
  {
    text: "Kinderschriftsteller",
    followingPunctuation: " ",
    translation: "children's author",
  },
  { text: "und", followingPunctuation: " ", translation: "and" },
  {
    text: "Bilderbüchler",
    followingPunctuation: " ",
    translation: "picture book maker",
  },
  { text: "aufzutreten", followingPunctuation: ". ", translation: "appear" },
  { text: "Fast", followingPunctuation: " ", translation: "almost" },
  { text: "wider", followingPunctuation: " ", translation: "against" },
  { text: "Willen", followingPunctuation: " ", translation: "will" },
  { text: "wurde", followingPunctuation: " ", translation: "was" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "dazu", followingPunctuation: " ", translation: "in addition" },
  { text: "gebracht", followingPunctuation: " ", translation: "brought" },
  { text: "als", followingPunctuation: " ", translation: "when" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "einst", followingPunctuation: " ", translation: "once" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "einer", followingPunctuation: " ", translation: "a" },
  { text: "literarischen", followingPunctuation: " ", translation: "literary" },
  {
    text: "Abendgesellschaft",
    followingPunctuation: " ",
    translation: "evening gathering",
  },
  { text: "mit", followingPunctuation: " ", translation: "with" },
  { text: "dem", followingPunctuation: " ", translation: "the" },
  { text: "einen", followingPunctuation: " ", translation: "one" },
  { text: "meiner", followingPunctuation: " ", translation: "my" },
  { text: "jetzigen", followingPunctuation: " ", translation: "current" },
  { text: "Verleger", followingPunctuation: " ", translation: "publisher" },
  { text: "gemütlich", followingPunctuation: " ", translation: "comfortably" },
  { text: "bei", followingPunctuation: " ", translation: "at" },
  { text: "der", followingPunctuation: " ", translation: "the" },
  { text: "Flasche", followingPunctuation: " ", translation: "bottle" },
  {
    text: "zusammensaß",
    followingPunctuation: ". ",
    translation: "sat together",
  },
  { text: "Und", followingPunctuation: " ", translation: "and" },
  { text: "so", followingPunctuation: " ", translation: "so" },
  { text: "trat", followingPunctuation: " ", translation: "stepped" },
  { text: "das", followingPunctuation: " ", translation: "the" },
  { text: "bescheidene", followingPunctuation: " ", translation: "modest" },
  { text: "Hauskind", followingPunctuation: " ", translation: "house child" },
  { text: "plötzlich", followingPunctuation: " ", translation: "suddenly" },
  { text: "hinaus", followingPunctuation: " ", translation: "out" },
  { text: "in", followingPunctuation: " ", translation: "in" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "weite", followingPunctuation: " ", translation: "wide" },
  { text: "offene", followingPunctuation: " ", translation: "open" },
  { text: "Welt", followingPunctuation: " ", translation: "world" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "machte", followingPunctuation: " ", translation: "made" },
  { text: "nun", followingPunctuation: " ", translation: "now" },
  { text: "seine", followingPunctuation: " ", translation: "his" },
  { text: "Reise", followingPunctuation: ", ", translation: "journey" },
  { text: "ich", followingPunctuation: " ", translation: "I" },
  { text: "kann", followingPunctuation: " ", translation: "can" },
  { text: "wohl", followingPunctuation: " ", translation: "well" },
  { text: "sagen", followingPunctuation: ", ", translation: "say" },
  { text: "um", followingPunctuation: " ", translation: "in order to" },
  { text: "die", followingPunctuation: " ", translation: "the" },
  { text: "Welt", followingPunctuation: ", ", translation: "world" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "heute", followingPunctuation: " ", translation: "today" },
  { text: "seit", followingPunctuation: " ", translation: "since" },
  {
    text: "einunddreißig",
    followingPunctuation: " ",
    translation: "thirty-one",
  },
  { text: "Jahren", followingPunctuation: " ", translation: "years" },
  { text: "bis", followingPunctuation: " ", translation: "until" },
  { text: "zur", followingPunctuation: " ", translation: "to the" },
  { text: "hundertsten", followingPunctuation: " ", translation: "hundredth" },
  { text: "Auflage", followingPunctuation: " ", translation: "edition" },
  { text: "gelangt", followingPunctuation: ". ", translation: "reached" },
  { text: "Von", followingPunctuation: " ", translation: "of" },
  {
    text: "Uebersetzungen",
    followingPunctuation: " ",
    translation: "translations",
  },
  { text: "ist", followingPunctuation: " ", translation: "is" },
  { text: "mir", followingPunctuation: " ", translation: "me" },
  { text: "bis", followingPunctuation: " ", translation: "until" },
  { text: "jetzt", followingPunctuation: " ", translation: "now" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  { text: "englische", followingPunctuation: ", ", translation: "English" },
  { text: "holländische", followingPunctuation: ", ", translation: "Dutch" },
  { text: "dänische", followingPunctuation: ", ", translation: "Danish" },
  { text: "schwedische", followingPunctuation: ", ", translation: "Swedish" },
  { text: "russische", followingPunctuation: ", ", translation: "Russian" },
  { text: "französische", followingPunctuation: ", ", translation: "French" },
  { text: "italienische", followingPunctuation: ", ", translation: "Italian" },
  { text: "spanische", followingPunctuation: " ", translation: "Spanish" },
  { text: "und", followingPunctuation: " ", translation: "and" },
  { text: "eine", followingPunctuation: " ", translation: "a" },
  {
    text: "portugiesische",
    followingPunctuation: " (",
    translation: "Portuguese",
  },
  { text: "für", followingPunctuation: " ", translation: "for" },
  { text: "Brasilien", followingPunctuation: ") ", translation: "Brazil" },
  { text: "zu", followingPunctuation: " ", translation: "to" },
  { text: "Gesicht", followingPunctuation: " ", translation: "sight" },
  { text: "gekommen", followingPunctuation: ".", translation: "come" },
];
